### ISSUE TITLE
Chat shifts up

### ISSUE THREAD

**Issue by bolte-io** [kulttuuri/quick-hotbar-mod#7]
When holding shift in my case to open Quick Hotbars preview of the inventory, the chat shifts up. Not sure if this was intentional or not however, reporting anyways.

Before holding shift:
![2020-10-03_17 39 20](https://user-images.githubusercontent.com/51535687/94996930-9143a300-059f-11eb-9908-6324c61ba536.png)

After holding shift:
![2020-10-03_17 39 25](https://user-images.githubusercontent.com/51535687/94996935-999bde00-059f-11eb-9ead-aa2672025eea.png)

**Comment by kulttuuri** [comment]
Yup, chat moves out of the way so it does not block view of the inventory! (or rather that's how I remember that I implemented it :D )
